version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: virality_postgres
    environment:
      POSTGRES_DB: virality_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: virality_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
