spring.application.name=virality-engine
server.port=8080

# H2 Database Config
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379